name: Publish Quarto site

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python (for pre-render script)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run pre-render (split bib)
        run: python scripts/split_bib.py
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render site
        run: quarto render
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}